### ISSUE TITLE
Allow everyone to see details of designs from within design page

### ISSUE THREAD

**Issue by rokumatsumoto** [rokumatsumoto/boyutluseyler#12]
- [ ] Add design page

- [ ] Place design details on page

- Name
- 3D model description
- 3D printing settings
- 3D model format
- Category
- Tags
- License
- Content preview component 
- Thumbnail list component 
- Content preview toggle button component

- [ ] Create content preview component #11 
- [ ] Create thumbnail list component #9
- [ ] Create content preview toggle button component #10
