### ISSUE TITLE
Allow users to upload files of 3D models from within new design page

### ISSUE THREAD

**Issue by rokumatsumoto** [rokumatsumoto/boyutluseyler#5]
Users should be able to upload 3D model photos and files to the application. 
Parent issue: #6 

- [ ] Minimum and maximum size of files should be considered

- [x] Staging and production Amazon S3 buckets should be created

- [x] CORS settings should be configured for Amazon S3 buckets

- [ ] Create specific Amazon IAM user for uploading and viewing files

- [ ] Only authenticated users can upload files, redirect user to login page gently if the user is not authenticated or session expired. 

- [ ] File name and extension should not be empty, special characters should be removed or inform user

- [ ] Generate unique key name for files. [Object Key and Metadata](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html)

- [ ] Create whitelist filter for file types

- [ ] Create connected uploader component #2

- [ ] Create draggable file list component  #3

- [ ] Create draggable file list item component #4
